# Header
menu:
  Home: /
  Archives: /archives
  Facebook: https://www.facebook.com/AsoulYang
  Github: https://github.com/Asoul
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
